<Project>
  <ItemGroup>
    <Compile Include="Upstream/Adapters/Features/ApplicationEvent.cs" />
    <Compile Include="Upstream/Adapters/Features/IBrowserCapabilitiesFactory.cs" />
    <Compile Include="Upstream/Adapters/Features/IHttpApplicationFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/IHttpBrowserCapabilityFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/IHttpHandlerFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/IHttpRequestInputStreamFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/IHttpRequestPathFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/IHttpResponseBufferingFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/IHttpResponseContentFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/IHttpResponseEndFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/IRequestExceptionFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/IRequestUserFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/ISessionStateFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/ITimestampFeature.cs" />
    <Compile Include="Upstream/Adapters/Features/ITransferRequestFeature.cs" />
    <Compile Include="Upstream/Adapters/IConfigurationAccessor.cs" />
    <Compile Include="Upstream/Adapters/IModuleRegistrar.cs" />
    <Compile Include="Upstream/Adapters/ITraceContext.cs" />
    <Compile Include="Upstream/Adapters/SessionState/ISessionState.cs" />
    <Compile Include="Upstream/AppConfiguration.cs" />
    <Compile Include="Upstream/Caching/Cache.cs" />
    <Compile Include="Upstream/Caching/CacheDependency.cs" />
    <Compile Include="Upstream/Caching/CacheExtensions.cs" />
    <Compile Include="Upstream/Caching/CacheItemPriority.cs" />
    <Compile Include="Upstream/Caching/CacheItemRemovedReason.cs" />
    <Compile Include="Upstream/Caching/CacheItemUpdateReason.cs" />
    <Compile Include="Upstream/Caching/ChangeMonitorExtensions.cs" />
    <Compile Include="Upstream/Configuration/BrowserCapabilitiesFactory.cs" />
    <Compile Include="Upstream/Configuration/HttpCapabilitiesBase.cs" />
    <Compile Include="Upstream/Constants.cs" />
    <Compile Include="Upstream/FeatureCollectionExtensions.cs" />
    <Compile Include="Upstream/Hosting/HostingEnvironment.cs" />
    <Compile Include="Upstream/Hosting/HostingEnvironmentAccessor.cs" />
    <Compile Include="Upstream/Hosting/IMapPathUtility.cs" />
    <Compile Include="Upstream/Hosting/MapPathUtility.cs" />
    <Compile Include="Upstream/Hosting/VirtualDirectory.cs" />
    <Compile Include="Upstream/Hosting/VirtualFile.cs" />
    <Compile Include="Upstream/Hosting/VirtualFileBase.cs" />
    <Compile Include="Upstream/Hosting/VirtualPathProvider.cs" />
    <Compile Include="Upstream/HtmlString.cs" />
    <Compile Include="Upstream/HttpApplication.cs" />
    <Compile Include="Upstream/HttpApplicationState.cs" />
    <Compile Include="Upstream/HttpApplicationStateBase.cs" />
    <Compile Include="Upstream/HttpApplicationStateWrapper.cs" />
    <Compile Include="Upstream/HttpBrowserCapabilities.cs" />
    <Compile Include="Upstream/HttpBrowserCapabilitiesBase.cs" />
    <Compile Include="Upstream/HttpBrowserCapabilitiesWrapper.cs" />
    <Compile Include="Upstream/HttpCachePolicy.cs" />
    <Compile Include="Upstream/HttpCachePolicyBase.cs" />
    <Compile Include="Upstream/HttpCachePolicyWrapper.cs" />
    <Compile Include="Upstream/HttpCacheRevalidation.cs" />
    <Compile Include="Upstream/HttpCacheVaryByContentEncodings.cs" />
    <Compile Include="Upstream/HttpCacheVaryByHeaders.cs" />
    <Compile Include="Upstream/HttpCacheVaryByParams.cs" />
    <Compile Include="Upstream/HttpCacheability.cs" />
    <Compile Include="Upstream/HttpCacheabilityLimits.cs" />
    <Compile Include="Upstream/HttpContext.cs" />
    <Compile Include="Upstream/HttpContextBase.cs" />
    <Compile Include="Upstream/HttpContextRequestServicesExtensions.cs" />
    <Compile Include="Upstream/HttpContextWrapper.cs" />
    <Compile Include="Upstream/HttpCookie.cs" />
    <Compile Include="Upstream/HttpCookieCollection.cs" />
    <Compile Include="Upstream/HttpDictionary.cs" />
    <Compile Include="Upstream/HttpException.cs" />
    <Compile Include="Upstream/HttpFileCollection.cs" />
    <Compile Include="Upstream/HttpFileCollectionBase.cs" />
    <Compile Include="Upstream/HttpFileCollectionWrapper.cs" />
    <Compile Include="Upstream/HttpModuleCollection.cs" />
    <Compile Include="Upstream/HttpPostedFile.cs" />
    <Compile Include="Upstream/HttpPostedFileBase.cs" />
    <Compile Include="Upstream/HttpPostedFileWrapper.cs" />
    <Compile Include="Upstream/HttpRequest.cs" />
    <Compile Include="Upstream/HttpRequestBase.cs" />
    <Compile Include="Upstream/HttpRequestWrapper.cs" />
    <Compile Include="Upstream/HttpResponse.cs" />
    <Compile Include="Upstream/HttpResponseBase.cs" />
    <Compile Include="Upstream/HttpResponseWrapper.cs" />
    <Compile Include="Upstream/HttpRuntime.cs" />
    <Compile Include="Upstream/HttpServerUtility.cs" />
    <Compile Include="Upstream/HttpServerUtilityBase.cs" />
    <Compile Include="Upstream/HttpServerUtilityWrapper.cs" />
    <Compile Include="Upstream/HttpTaskAsyncHandler.cs" />
    <Compile Include="Upstream/HttpUnhandledException.cs" />
    <Compile Include="Upstream/IHtmlString.cs" />
    <Compile Include="Upstream/IHttpAsyncHandler.cs" />
    <Compile Include="Upstream/IHttpHandler.cs" />
    <Compile Include="Upstream/IHttpHandlerFactory.cs" />
    <Compile Include="Upstream/IHttpModule.cs" />
    <Compile Include="Upstream/IReadOnlySessionState.cs" />
    <Compile Include="Upstream/IRequiresSessionState.cs" />
    <Compile Include="Upstream/ISubscriptionToken.cs" />
    <Compile Include="Upstream/Internal/FormCollectionReadOnlyDictionary.cs" />
    <Compile Include="Upstream/Internal/HttpValueCollection.cs" />
    <Compile Include="Upstream/Internal/NameValueCollectionExtensions.cs" />
    <Compile Include="Upstream/Internal/NoGetByIntNameValueCollection.cs" />
    <Compile Include="Upstream/Internal/NonGenericCollectionWrapper.cs" />
    <Compile Include="Upstream/Internal/NonGenericDictionaryWrapper.cs" />
    <Compile Include="Upstream/Internal/ParamsCollection.cs" />
    <Compile Include="Upstream/Internal/QueryCollectionReadOnlyDictionary.cs" />
    <Compile Include="Upstream/Internal/ServerVariablesNameValueCollection.cs" />
    <Compile Include="Upstream/Internal/StringValuesDictionaryNameValueCollection.cs" />
    <Compile Include="Upstream/Internal/StringValuesReadOnlyDictionaryNameValueCollection.cs" />
    <Compile Include="Upstream/Properties/PropertyInfo.cs" />
    <Compile Include="Upstream/ReadEntityBodyMode.cs" />
    <Compile Include="Upstream/RequestNotification.cs" />
    <Compile Include="Upstream/SameSiteMode.cs" />
    <Compile Include="Upstream/Security/MachineKey.cs" />
    <Compile Include="Upstream/SessionState/HttpSessionState.cs" />
    <Compile Include="Upstream/SessionState/HttpSessionStateBase.cs" />
    <Compile Include="Upstream/SessionState/HttpSessionStateWrapper.cs" />
    <Compile Include="Upstream/SessionState/SessionStateBehavior.cs" />
    <Compile Include="Upstream/SessionState/SessionStateMode.cs" />
    <Compile Include="Upstream/System/Diagnostics/CodeAnalysis/ExperimentalAttribute.cs" />
    <Compile Include="Upstream/SystemWebAdaptersConversionExtensions.cs" />
    <Compile Include="Upstream/SystemWebAdaptersOptions.cs" />
    <Compile Include="Upstream/TraceContext.cs" />
    <Compile Include="Upstream/Utilities/StringUtil.cs" />
    <Compile Include="Upstream/Utilities/UrlPath.cs" />
    <Compile Include="Upstream/VirtualPathUtility.cs" />
    <Compile Include="Upstream/VirtualPathUtilityImpl.cs" />
  </ItemGroup>
</Project>
