<Project>
  <ItemGroup>
    <Compile Include="../../src/CommonResources.Designer.cs" />
    <Compile Include="../../src/Common/HashCodeCombiner.cs" />
    <Compile Include="../../src/GlobalSuppressions.cs" />
    <Compile Include="../../src/System.Web.Razor/DocumentParseCompleteEventArgs.cs" />
    <Compile Include="../../src/System.Web.Razor/Editor/AutoCompleteEditHandler.cs" />
    <Compile Include="../../src/System.Web.Razor/Editor/BackgroundParser.cs" />
    <Compile Include="../../src/System.Web.Razor/Editor/RazorEditorTrace.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/AttributeBlockCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/CodeWriterExtensions.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/DynamicAttributeBlockCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/ExpressionRenderingMode.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/LiteralAttributeCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/RazorCommentCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/SetLayoutCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Editor/SingleLineMarkupEditHandler.cs" />
    <Compile Include="../../src/System.Web.Razor/Editor/SpanEditHandler.cs" />
    <Compile Include="../../src/System.Web.Razor/Editor/EditResult.cs" />
    <Compile Include="../../src/System.Web.Razor/Editor/ImplicitExpressionEditHandler.cs" />
    <Compile Include="../../src/System.Web.Razor/Editor/EditorHints.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/AddImportCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/BlockCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/CodeGeneratorPaddingHelper.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/CodeGeneratorContext.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/CodeWriter.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/BaseCodeWriter.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/RazorDirectiveAttributeCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/CSharpCodeWriter.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/ExpressionCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/GeneratedClassContext.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/HybridCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/IBlockCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/ISpanCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/MarkupCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/ResolveUrlCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/SetBaseTypeCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/HelperCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/SectionCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/SetVBOptionCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/SpanCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/StatementCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/TemplateBlockCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/TypeMemberCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/VBCodeWriter.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/BalancingModes.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/CallbackVisitor.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/ConditionalAttributeCollapser.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/CSharpCodeParser.Directives.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/CSharpCodeParser.Statements.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/CSharpCodeParser.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/CSharpLanguageCharacteristics.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/HtmlLanguageCharacteristics.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/HtmlMarkupParser.Block.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/HtmlMarkupParser.Document.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/HtmlMarkupParser.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/HtmlMarkupParser.Section.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/ISyntaxTreeRewriter.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/LanguageCharacteristics.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/MarkupCollapser.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/MarkupRewriter.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/ParserHelpers.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/ParserVisitor.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/ParserVisitorExtensions.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxConstants.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxTree/AcceptedCharacters.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxTree/BlockBuilder.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxTree/EquivalenceComparer.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxTree/SpanBuilder.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/TextReaderExtensions.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/TokenizerBackedParser.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/TokenizerBackedParser.Helpers.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/VBCodeParser.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/VBCodeParser.Directives.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/VBLanguageCharacteristics.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/WhitespaceRewriter.cs" />
    <Compile Include="../../src/System.Web.Razor/PartialParseResult.cs" />
    <Compile Include="../../src/System.Web.Razor/RazorDebugHelpers.cs" />
    <Compile Include="../../src/System.Web.Razor/RazorDirectiveAttribute.cs" />
    <Compile Include="../../src/System.Web.Razor/RazorEditorParser.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/CodeGenerationCompleteEventArgs.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/GeneratedCodeMapping.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/RazorCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/GeneratorResults.cs" />
    <Compile Include="../../src/System.Web.Razor/RazorEngineHost.cs" />
    <Compile Include="../../src/System.Web.Razor/RazorTemplateEngine.cs" />
    <Compile Include="../../src/System.Web.Razor/StateMachine.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/BufferingTextReader.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/LookaheadToken.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/LocationTagged.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/SeekableTextReader.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/LineTrackingStringBuffer.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/LookaheadTextReader.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/TextExtensions.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/TextBufferReader.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/TextDocumentReader.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/ITokenizer.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/ISymbol.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/KnownSymbolType.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/SymbolExtensions.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/SymbolTypeSuppressions.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/TokenizerView.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/VBKeywordDetector.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/VBHelpers.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/CSharpHelpers.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/CSharpKeywordDetector.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/CSharpTokenizer.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/HtmlTokenizer.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/VBKeyword.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/VBSymbol.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/VBSymbolType.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/CSharpKeyword.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/CSharpSymbol.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/CSharpSymbolType.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/HtmlSymbol.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/HtmlSymbolType.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Symbols/SymbolBase.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/Tokenizer.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/VBTokenizer.cs" />
    <Compile Include="../../src/System.Web.Razor/Tokenizer/XmlHelpers.cs" />
    <Compile Include="../../src/System.Web.Razor/Utils/CharUtils.cs" />
    <Compile Include="../../src/System.Web.Razor/VBRazorCodeLanguage.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/CSharpRazorCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxTree/BlockType.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxTree/Block.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxTree/RazorError.cs" />
    <Compile Include="../../src/System.Web.Razor/ParserResults.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxTree/SyntaxTreeNode.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxTree/SpanKind.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/ParserContext.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/RazorParser.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/ITextBuffer.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/SourceLocationTracker.cs" />
    <Compile Include="../../src/System.Web.Razor/RazorCodeLanguage.cs" />
    <Compile Include="../../src/System.Web.Razor/CSharpRazorCodeLanguage.cs" />
    <Compile Include="../../src/System.Web.Razor/Utils/DisposableAction.cs" />
    <Compile Include="../../src/System.Web.Razor/Utils/EnumUtil.cs" />
    <Compile Include="../../src/System.Web.Razor/Utils/EnumeratorExtensions.cs" />
    <Compile Include="../../src/System.Web.Razor/GlobalSuppressions.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/ParserBase.cs" />
    <Compile Include="../../src/System.Web.Razor/Resources/RazorResources.Designer.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/SourceLocation.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/TextChange.cs" />
    <Compile Include="../../src/System.Web.Razor/Text/TextChangeType.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/SyntaxTree/Span.cs" />
    <Compile Include="../../src/System.Web.Razor/Generator/VBRazorCodeGenerator.cs" />
    <Compile Include="../../src/System.Web.Razor/Parser/VBCodeParser.Statements.cs" />
  </ItemGroup>
</Project>
