<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../PackageMetadata.props" />
  <PropertyGroup><PackageId>Mvc5.Native.Experimental</PackageId></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="System.CodeDom" Version="10.0.1" />
    <PackageReference Include="System.Runtime.Caching" Version="10.0.0" />
    <ProjectReference Include="../../Mvc/System.Web.Mvc.Net10.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <None Include="../../Mvc/bin/$(Configuration)/net10.0/System.Web.Mvc.dll" Pack="true" PackagePath="lib/net10.0/" />
    <None Include="../../Razor/bin/$(Configuration)/net10.0/System.Web.Razor.dll" Pack="true" PackagePath="lib/net10.0/" />
    <None Include="../../SystemWebAdapters/bin/$(Configuration)/net10.0/Microsoft.AspNetCore.SystemWebAdapters.dll" Pack="true" PackagePath="lib/net10.0/" />
    <None Include="Mvc5.Native.Experimental.targets" Pack="true" PackagePath="buildTransitive/net10.0/" />
  </ItemGroup>
</Project>
